// Auto-generated by scripts/gen-cli-reference.ts — do not edit by hand.
//
// CLI Reference Generator
// ========================
// This script reads the mogplex CLI command registry from the sibling
// mogplex-cli repo and generates MDX reference pages for the production-ready
// standalone subcommands, plus a single summary page for the additional names
// that still appear in `mogplex --help` but are not yet real standalone
// entrypoints.
//
// Registry location: ../mogplex-cli/packages/cli/src/subcommands.ts
//   - SUBCOMMAND_NAMES: array of canonical command names
//   - HIDDEN_SUBCOMMANDS: set of internal commands to exclude
//   - EXPERIMENTAL_SUBCOMMANDS: set of experimental commands (tagged)
//
// Summaries: ../mogplex-cli/packages/cli/src/help.ts
//   - SUMMARIES: Record<SubcommandName, string>
//
// Extraction approach: We import the modules directly via tsx at build time.
// This keeps the docs in sync with the actual CLI registry without needing
// to shell out to `mogplex --help` (which would require the CLI to be built).

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = path.resolve(__dirname, "..");
const CLI_SRC = path.resolve(DOCS_ROOT, "..", "mogplex-cli", "packages", "cli", "src");
const OUTPUT_DIR = path.join(DOCS_ROOT, "content", "docs", "cli", "commands");

// ---------------------------------------------------------------------------
// Registry types (mirrored from CLI to avoid import issues)
// ---------------------------------------------------------------------------

type SubcommandName = string;

interface CommandRegistry {
  names: readonly SubcommandName[];
  hidden: ReadonlySet<SubcommandName>;
  experimental: ReadonlySet<SubcommandName>;
  implemented: ReadonlySet<SubcommandName>;
  summaries: Readonly<Record<string, string>>;
  aliases: Readonly<Record<string, SubcommandName>>;
}

// ---------------------------------------------------------------------------
// Parse the CLI source files to extract registry data
// ---------------------------------------------------------------------------

function extractQuotedSet(content: string, exportName: string): Set<string> {
  const pattern = new RegExp(
    `export const ${exportName}[^=]*=\\s*new Set\\(\\[([\\s\\S]*?)\\]\\)`
  );
  const match = content.match(pattern);
  const out = new Set<string>();
  if (!match?.[1]) return out;
  for (const m of match[1].matchAll(/"([^"]+)"/g)) {
    if (m[1]) out.add(m[1]);
  }
  return out;
}

function parseSubcommandsFile(content: string): {
  names: string[];
  hidden: Set<string>;
  experimental: Set<string>;
  implemented: Set<string>;
  aliases: Record<string, string>;
} {
  // Extract SUBCOMMAND_NAMES array
  const namesMatch = content.match(
    /export const SUBCOMMAND_NAMES\s*=\s*\[([\s\S]*?)\]\s*as const/
  );
  const names: string[] = [];
  if (namesMatch?.[1]) {
    const matches = namesMatch[1].matchAll(/"([^"]+)"/g);
    for (const m of matches) {
      if (m[1]) names.push(m[1]);
    }
  }

  const hidden = extractQuotedSet(content, "HIDDEN_SUBCOMMANDS");
  const experimental = extractQuotedSet(content, "EXPERIMENTAL_SUBCOMMANDS");
  const implemented = extractQuotedSet(content, "IMPLEMENTED_SUBCOMMANDS");

  // Extract SUBCOMMAND_ALIASES
  // Handles both quoted keys ("cloud-tasks") and unquoted keys (e, a)
  const aliasMatch = content.match(
    /export const SUBCOMMAND_ALIASES[^{]*\{([\s\S]*?)\}/
  );
  const aliases: Record<string, string> = {};
  if (aliasMatch?.[1]) {
    // Match quoted keys: "cloud-tasks": "cloud"
    const quotedMatches = aliasMatch[1].matchAll(/"([^"]+)"\s*:\s*"([^"]+)"/g);
    for (const m of quotedMatches) {
      if (m[1] && m[2]) aliases[m[1]] = m[2];
    }
    // Match unquoted keys: e: "exec"
    const unquotedMatches = aliasMatch[1].matchAll(/\b([a-z])\s*:\s*"([^"]+)"/g);
    for (const m of unquotedMatches) {
      if (m[1] && m[2]) aliases[m[1]] = m[2];
    }
  }

  return { names, hidden, experimental, implemented, aliases };
}

function parseHelpFile(content: string): Record<string, string> {
  // Extract SUMMARIES record
  const summariesMatch = content.match(
    /const SUMMARIES[^{]*\{([\s\S]*?)\};/
  );
  const summaries: Record<string, string> = {};
  if (summariesMatch?.[1]) {
    const matches = summariesMatch[1].matchAll(
      /["']?([a-z-]+)["']?\s*:\s*"([^"]+)"/g
    );
    for (const m of matches) {
      if (m[1] && m[2]) summaries[m[1]] = m[2];
    }
  }
  return summaries;
}

function loadRegistry(): CommandRegistry | null {
  // Only skip when the CLI source tree itself is absent (e.g. Vercel builds
  // that don't check out the sibling mogplex-cli repo). If the tree exists
  // but required files are missing, fail loudly — that's a real breakage.
  if (!fs.existsSync(CLI_SRC)) {
    return null;
  }

  const subcommandsPath = path.join(CLI_SRC, "subcommands.ts");
  const helpPath = path.join(CLI_SRC, "help.ts");

  if (!fs.existsSync(subcommandsPath)) {
    throw new Error(`CLI subcommands.ts not found at ${subcommandsPath}`);
  }
  if (!fs.existsSync(helpPath)) {
    throw new Error(`CLI help.ts not found at ${helpPath}`);
  }

  const subcommandsContent = fs.readFileSync(subcommandsPath, "utf-8");
  const helpContent = fs.readFileSync(helpPath, "utf-8");

  const { names, hidden, experimental, implemented, aliases } =
    parseSubcommandsFile(subcommandsContent);
  const summaries = parseHelpFile(helpContent);

  return { names, hidden, experimental, implemented, summaries, aliases };
}

// ---------------------------------------------------------------------------
// MDX generation
// ---------------------------------------------------------------------------

interface CommandDoc {
  name: string;
  summary: string;
  isExperimental: boolean;
  isImplemented: boolean;
  aliases: string[];
}

interface RelatedDoc {
  label: string;
  href: string;
}

const EXTRA_SECTIONS: Readonly<Record<string, string[]>> = {
  exec: [
    "## How It Works",
    "",
    "`mogplex exec` runs one non-interactive task and exits with the engine's final exit code.",
    "The prompt is built from the remaining arguments after `exec`.",
    "",
    "If the prompt starts with `/`, the CLI routes it through the slash-command registry instead of the normal engine prompt path.",
    "",
    "## Common Uses",
    "",
    "```bash",
    'mogplex exec "review the staged diff for regressions"',
    'mogplex exec "summarize the repo structure and likely entrypoints"',
    'mogplex exec "/status"',
    "```",
    "",
    "## Related Entry Points",
    "",
    "- `mogplex \"<prompt>\"` is a shortcut for a one-off non-interactive run without spelling `exec`.",
    "- `mogplex` without a prompt launches the interactive terminal UI.",
    "",
    "## Output",
    "",
    "For automation or scripting, combine `exec` with the global output flags such as `--output json`, `--json`, or `--jsonl`.",
  ],
  login: [
    "## Current Behavior",
    "",
    "The current build supports three top-level login paths:",
    "",
    "- `mogplex login` opens the same interactive auth chooser as bare `mogplex`",
    "- `mogplex login mogplex` routes to the same chooser",
    "- `mogplex login status` prints a safe summary of stored credentials without revealing secret material",
    "",
    "## What It Stores",
    "",
    "Browser sign-in stores a Mogplex token in `~/.mogplex/auth.json`.",
    "API-key login stores the selected provider credential there instead.",
    "",
    "## Common Uses",
    "",
    "```bash",
    "mogplex login",
    "mogplex login status",
    "```",
    "",
    "For the full credential precedence rules, use the [Authentication guide](/cli/guides/authentication).",
  ],
  slash: [
    "## Current Behavior",
    "",
    "As a standalone subcommand, `mogplex slash` currently supports listing the slash registry.",
    "If you omit the nested subcommand, it behaves the same as `mogplex slash list`.",
    "",
    "## Common Uses",
    "",
    "```bash",
    "mogplex slash list",
    "mogplex slash list --json",
    'mogplex exec "/status"',
    'mogplex exec "/mcp"',
    "```",
    "",
    "## Important Distinction",
    "",
    "- Use `mogplex slash list` to inspect the registry from the shell.",
    "- Use `mogplex exec \"/...\"` to run a slash command non-interactively.",
    "- Use a live `mogplex` session when you want the normal interactive slash workflow.",
  ],
};

const COMMAND_USE_TODAY: Readonly<Record<string, string[]>> = {
  review: [
    'Use `mogplex exec "review the staged diff for regressions"` for one-off code review.',
  ],
  logout: [
    "Use `/logout` inside a live session to remove the stored credential.",
    "Run `mogplex login status` afterward if you want to confirm what is still stored.",
  ],
  mcp: [
    'Use `mogplex exec "/mcp"` or `/mcp` inside a session to inspect configured MCP servers.',
    "Manage shared MCP definitions in [Settings](/web/settings).",
  ],
  "mcp-server": [
    "Use [Settings](/web/settings) for shared MCP configuration.",
    'Use `mogplex exec "/mcp"` for the current local inspection path.',
  ],
  plugin: [
    "Treat this as a reserved command name for now.",
    "The production-safe customization paths today are repo instructions, slash commands, and the hosted settings surfaces.",
  ],
  app: [
    "The CLI and web app are the production surfaces today.",
    "Ignore this command unless a release note explicitly tells you to use it.",
  ],
  "app-server": [
    "This is an experimental help-surface entry.",
    "Do not build automation around it yet.",
  ],
  completion: [
    "Shell completion generation is not yet a stable standalone workflow in the current build.",
    "Use `mogplex --help` as the current source of truth for available commands and flags.",
  ],
  sandbox: [
    "Use `/sandbox` inside a live session.",
    'If you need a shell entrypoint, try `mogplex exec "/sandbox ..."` in environments where the slash command is available.',
  ],
  debug: [
    "Use `/logs`, `/status`, and [Observability](/web/observability) for current debugging workflows.",
  ],
  apply: [
    "Use an interactive `mogplex` session and inspect or apply changes from the active workflow directly.",
  ],
  resume: [
    "Use the interactive session and existing session history today.",
    "Do not script against `mogplex resume` yet.",
  ],
  fork: [
    "Use a new `mogplex` session or the existing interactive workflow today.",
    "Do not script against `mogplex fork` yet.",
  ],
  cloud: [
    "Use the [web app](/web) and [Observability](/web/observability) for hosted activity today.",
  ],
  "exec-server": [
    "Treat this as an experimental help-surface entry unless a release note explicitly tells you to use it.",
  ],
  features: [
    "Use the global `--feature KEY[=VAL]` flag on supported commands instead of relying on a standalone `mogplex features` workflow.",
  ],
};

const COMMAND_RELATED_DOCS: Readonly<Record<string, RelatedDoc[]>> = {
  exec: [
    { label: "Exec Mode", href: "/cli/guides/exec-mode" },
    { label: "Quickstart", href: "/cli/quickstart" },
  ],
  review: [{ label: "Exec Mode", href: "/cli/guides/exec-mode" }],
  login: [
    { label: "Authentication", href: "/cli/guides/authentication" },
    { label: "Quickstart", href: "/cli/quickstart" },
  ],
  logout: [
    { label: "Authentication", href: "/cli/guides/authentication" },
    { label: "Slash Commands", href: "/cli/guides/slash-commands" },
  ],
  mcp: [
    { label: "Slash Commands", href: "/cli/guides/slash-commands" },
    { label: "Web Settings", href: "/web/settings" },
  ],
  "mcp-server": [{ label: "Web Settings", href: "/web/settings" }],
  sandbox: [{ label: "Slash Commands", href: "/cli/guides/slash-commands" }],
  debug: [
    { label: "Slash Commands", href: "/cli/guides/slash-commands" },
    { label: "Observability", href: "/web/observability" },
  ],
  cloud: [
    { label: "Web App Overview", href: "/web" },
    { label: "Observability", href: "/web/observability" },
  ],
  slash: [
    { label: "Slash Commands", href: "/cli/guides/slash-commands" },
    { label: "Quickstart", href: "/cli/quickstart" },
  ],
};

function getStatusText(cmd: CommandDoc): string {
  if (cmd.isImplemented && cmd.isExperimental) {
    return "Implemented experimental standalone command.";
  }
  if (cmd.isImplemented) {
    return "Implemented standalone command.";
  }
  if (cmd.isExperimental) {
    return "Help-surface-only experimental command name.";
  }
  return "Help-surface-only reserved command name.";
}

function getFallbackWorkarounds(cmd: CommandDoc): string[] {
  const specific = COMMAND_USE_TODAY[cmd.name];
  if (specific && specific.length > 0) {
    return specific;
  }
  return [
    "If you need this capability today, prefer a fully implemented path such as `mogplex exec`, `mogplex login`, `mogplex slash list`, or an in-session slash command.",
    "Treat this page as documentation for the name the binary advertises, not as a guarantee that the standalone path is production-ready yet.",
  ];
}

function getRelatedDocs(cmd: CommandDoc): RelatedDoc[] {
  return [
    ...(COMMAND_RELATED_DOCS[cmd.name] ?? []),
    { label: "All commands", href: "/cli/commands" },
  ];
}

function generateReservedNamesMdx(commands: CommandDoc[]): string {
  const reserved = commands.filter((cmd) => !cmd.isExperimental);
  const experimental = commands.filter((cmd) => cmd.isExperimental);
  const lines: string[] = [];

  lines.push("---");
  lines.push("title: Reserved Names");
  lines.push(
    "description: Names shown in `mogplex --help` that are not yet production-ready standalone commands."
  );
  lines.push("---");
  lines.push("");
  lines.push("{/* Auto-generated by scripts/gen-cli-reference.ts — do not edit by hand. */}");
  lines.push("");
  lines.push(
    "The CLI help surface currently includes some command names that are not yet fully wired as standalone entrypoints."
  );
  lines.push(
    "The docs keep these names visible because they are part of the published help surface, but they should not dominate the main command navigation."
  );
  lines.push("");
  lines.push("Use the implemented standalone commands for production workflows:");
  lines.push("");
  lines.push("- [`exec`](/cli/commands/exec)");
  lines.push("- [`login`](/cli/commands/login)");
  lines.push("- [`slash`](/cli/commands/slash)");
  lines.push("");
  lines.push("## Reserved names");
  lines.push("");

  if (reserved.length > 0) {
    for (const cmd of reserved) {
      lines.push(
        `- \`${cmd.name}\` — ${cmd.summary} ${getFallbackWorkarounds(cmd).join(" ")}`
      );
    }
  } else {
    lines.push("No reserved help-surface names are currently listed.");
  }

  lines.push("");
  lines.push("## Experimental names");
  lines.push("");

  if (experimental.length > 0) {
    for (const cmd of experimental) {
      lines.push(
        `- \`${cmd.name}\` — ${cmd.summary} ${getFallbackWorkarounds(cmd).join(" ")}`
      );
    }
  } else {
    lines.push("No experimental help-surface names are currently listed.");
  }

  lines.push("");
  lines.push("## Why this page exists");
  lines.push("");
  lines.push(
    "This page is the honest place to document the additional command names exposed by `mogplex --help` without pretending each one is already a production-ready standalone workflow."
  );
  lines.push("");
  lines.push("## See also");
  lines.push("");
  lines.push("- [Commands overview](/cli/commands)");
  lines.push("- [Exec Mode](/cli/guides/exec-mode)");
  lines.push("- [Slash Commands](/cli/guides/slash-commands)");
  lines.push("");

  return lines.join("\n");
}

function generateMdx(cmd: CommandDoc): string {
  const lines: string[] = [];

  // Front matter
  lines.push("---");
  lines.push(`title: ${cmd.name}`);
  lines.push(`description: ${cmd.summary}`);
  lines.push("---");
  lines.push("");
  lines.push("{/* Auto-generated by scripts/gen-cli-reference.ts — do not edit by hand. */}");
  lines.push("");

  // Experimental badge
  if (cmd.isExperimental) {
    lines.push("> **Experimental**: This command is experimental and may change.");
    lines.push("");
  }

  // Status
  lines.push("## Status");
  lines.push("");
  lines.push(getStatusText(cmd));
  lines.push("");

  // Synopsis
  lines.push("## Synopsis");
  lines.push("");
  lines.push("```bash");
  lines.push(`mogplex ${cmd.name} [OPTIONS] [ARGS]`);
  lines.push("```");
  lines.push("");

  // Description
  lines.push("## Description");
  lines.push("");
  lines.push(cmd.summary);
  lines.push("");

  // "Not yet implemented" notice is driven by the CLI's exported
  // IMPLEMENTED_SUBCOMMANDS set (packages/cli/src/subcommands.ts), so adding
  // a dispatcher in the CLI automatically updates the generated docs.
  if (!cmd.isImplemented) {
    lines.push("## Current Implementation Status");
    lines.push("");
    lines.push(
      `The command name is present in the CLI help surface, but the standalone \`mogplex ${cmd.name}\` path is not wired yet in the current build.`,
    );
    lines.push(
      `At the moment, running it can return \`Subcommand '${cmd.name}' is not yet implemented.\``,
    );
    lines.push("");

    lines.push("## What To Use Today");
    lines.push("");
    for (const item of getFallbackWorkarounds(cmd)) {
      lines.push(`- ${item}`);
    }
    lines.push("");

    lines.push("## Why This Page Exists");
    lines.push("");
    lines.push(
      "The docs intentionally track the names exposed by `mogplex --help`, even when a standalone command is still reserved or partial.",
    );
    lines.push(
      "That makes it clear which names are already part of the public help surface and which ones are not yet production-ready entrypoints.",
    );
    lines.push("");
  }

  // Aliases
  if (cmd.aliases.length > 0) {
    lines.push("## Aliases");
    lines.push("");
    for (const alias of cmd.aliases) {
      lines.push(`- \`${alias}\``);
    }
    lines.push("");
  }

  const extraSections = EXTRA_SECTIONS[cmd.name];
  if (extraSections) {
    lines.push(...extraSections);
    lines.push("");
  }

  // Run `mogplex <cmd> --help` hint — full option lists are owned by the CLI's own help output,
  // not duplicated here, so they never drift.
  lines.push("## Options");
  lines.push("");
  lines.push(`Run \`mogplex ${cmd.name} --help\` to see all supported flags.`);
  lines.push("");

  // See also
  lines.push("## See also");
  lines.push("");
  for (const related of getRelatedDocs(cmd)) {
    lines.push(`- [${related.label}](${related.href})`);
  }
  lines.push("");

  return lines.join("\n");
}

function generateMetaJson(
  implementedCommandNames: string[],
  includeReservedNames: boolean
): string {
  const pages = [
    "index",
    ...implementedCommandNames,
    ...(includeReservedNames ? ["reserved-names"] : []),
  ];
  const meta = {
    title: "Commands",
    defaultOpen: true,
    pages,
  };
  return JSON.stringify(meta, null, 2) + "\n";
}

// ---------------------------------------------------------------------------
// File writing helpers (idempotent - only writes if content changed)
// ---------------------------------------------------------------------------

function writeFileIfChanged(filePath: string, content: string): boolean {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, "utf-8");
    if (existing === content) {
      return false;
    }
  }
  fs.writeFileSync(filePath, content);
  return true;
}

function removeFileIfExists(filePath: string): boolean {
  if (!fs.existsSync(filePath)) return false;
  fs.unlinkSync(filePath);
  return true;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  console.log("Loading CLI command registry...");
  const registry = loadRegistry();

  if (!registry) {
    console.warn(
      `CLI source tree not found at ${CLI_SRC}. Skipping CLI reference generation; keeping existing generated files.`
    );
    return;
  }

  // Filter to visible commands only
  const visibleCommands = registry.names.filter(
    (name) => !registry.hidden.has(name)
  );
  const implementedCommands = visibleCommands.filter((name) =>
    registry.implemented.has(name)
  );
  const reservedCommands = visibleCommands.filter(
    (name) => !registry.implemented.has(name)
  );

  if (visibleCommands.length === 0) {
    console.error("No discoverable commands found in CLI registry.");
    console.log("Creating placeholder page...");

    const placeholderMdx = `---
title: Commands
description: CLI command reference (placeholder)
---

{/* Auto-generated by scripts/gen-cli-reference.ts — do not edit by hand. */}

No commands were discovered from the CLI registry. This may indicate the registry
structure has changed.
`;
    writeFileIfChanged(path.join(OUTPUT_DIR, "placeholder.mdx"), placeholderMdx);
    writeFileIfChanged(
      path.join(OUTPUT_DIR, "meta.json"),
      JSON.stringify({ title: "Commands", defaultOpen: true, pages: ["index", "placeholder"] }, null, 2) + "\n"
    );
    process.exit(0);
  }

  console.log(`Found ${visibleCommands.length} visible commands.`);

  // Build alias lookup (reverse: command -> aliases)
  const aliasesByCommand: Record<string, string[]> = {};
  for (const [alias, cmd] of Object.entries(registry.aliases)) {
    if (!aliasesByCommand[cmd]) aliasesByCommand[cmd] = [];
    aliasesByCommand[cmd].push(alias);
  }

  // Generate MDX for each implemented command
  const generatedNames: string[] = [];
  let changedCount = 0;
  for (const name of implementedCommands) {
    const cmd: CommandDoc = {
      name,
      summary: registry.summaries[name] ?? "No description available.",
      isExperimental: registry.experimental.has(name),
      isImplemented: registry.implemented.has(name),
      aliases: aliasesByCommand[name] ?? [],
    };

    const mdxContent = generateMdx(cmd);
    const outputPath = path.join(OUTPUT_DIR, `${name}.mdx`);
    const changed = writeFileIfChanged(outputPath, mdxContent);
    generatedNames.push(name);
    if (changed) {
      changedCount++;
      console.log(`  Generated: ${name}.mdx`);
    }
  }

  if (reservedCommands.length > 0) {
    const reservedDocs = reservedCommands.map((name) => ({
      name,
      summary: registry.summaries[name] ?? "No description available.",
      isExperimental: registry.experimental.has(name),
      isImplemented: false,
      aliases: aliasesByCommand[name] ?? [],
    }));
    const reservedContent = generateReservedNamesMdx(reservedDocs);
    const reservedPath = path.join(OUTPUT_DIR, "reserved-names.mdx");
    const changed = writeFileIfChanged(reservedPath, reservedContent);
    if (changed) {
      changedCount++;
      console.log("  Generated: reserved-names.mdx");
    }
  }

  const keepFiles = new Set<string>([
    "index.mdx",
    ...generatedNames.map((name) => `${name}.mdx`),
    ...(reservedCommands.length > 0 ? ["reserved-names.mdx"] : []),
  ]);

  for (const entry of fs.readdirSync(OUTPUT_DIR)) {
    if (!entry.endsWith(".mdx")) continue;
    if (keepFiles.has(entry)) continue;
    const removed = removeFileIfExists(path.join(OUTPUT_DIR, entry));
    if (removed) {
      changedCount++;
      console.log(`  Removed: ${entry}`);
    }
  }

  // Generate meta.json
  const metaContent = generateMetaJson(
    generatedNames,
    reservedCommands.length > 0
  );
  const metaChanged = writeFileIfChanged(path.join(OUTPUT_DIR, "meta.json"), metaContent);
  if (metaChanged) {
    changedCount++;
    console.log(
      `  Generated: meta.json with ${generatedNames.length + 1 + (reservedCommands.length > 0 ? 1 : 0)} pages`
    );
  }

  if (changedCount === 0) {
    console.log(`Done. All ${generatedNames.length} command pages are up to date.`);
  } else {
    console.log(`Done. Updated ${changedCount} file(s).`);
  }
}

main();
