// Auto-generated by scripts/gen-cli-reference.ts — do not edit by hand.
//
// CLI Reference Generator
// ========================
// This script reads the mogplex CLI command registry from the sibling
// mogplex-cli repo and generates one MDX page per subcommand.
//
// Registry location: ../mogplex-cli/packages/cli/src/subcommands.ts
//   - SUBCOMMAND_NAMES: array of canonical command names
//   - HIDDEN_SUBCOMMANDS: set of internal commands to exclude
//   - EXPERIMENTAL_SUBCOMMANDS: set of experimental commands (tagged)
//
// Summaries: ../mogplex-cli/packages/cli/src/help.ts
//   - SUMMARIES: Record<SubcommandName, string>
//
// Extraction approach: We import the modules directly via tsx at build time.
// This keeps the docs in sync with the actual CLI registry without needing
// to shell out to `mogplex --help` (which would require the CLI to be built).

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = path.resolve(__dirname, "..");
const CLI_SRC = path.resolve(DOCS_ROOT, "..", "mogplex-cli", "packages", "cli", "src");
const OUTPUT_DIR = path.join(DOCS_ROOT, "content", "docs", "cli", "commands");

// ---------------------------------------------------------------------------
// Registry types (mirrored from CLI to avoid import issues)
// ---------------------------------------------------------------------------

type SubcommandName = string;

interface CommandRegistry {
  names: readonly SubcommandName[];
  hidden: ReadonlySet<SubcommandName>;
  experimental: ReadonlySet<SubcommandName>;
  summaries: Readonly<Record<string, string>>;
  aliases: Readonly<Record<string, SubcommandName>>;
}

// ---------------------------------------------------------------------------
// Parse the CLI source files to extract registry data
// ---------------------------------------------------------------------------

function parseSubcommandsFile(content: string): {
  names: string[];
  hidden: Set<string>;
  experimental: Set<string>;
  aliases: Record<string, string>;
} {
  // Extract SUBCOMMAND_NAMES array
  const namesMatch = content.match(
    /export const SUBCOMMAND_NAMES\s*=\s*\[([\s\S]*?)\]\s*as const/
  );
  const names: string[] = [];
  if (namesMatch?.[1]) {
    const matches = namesMatch[1].matchAll(/"([^"]+)"/g);
    for (const m of matches) {
      if (m[1]) names.push(m[1]);
    }
  }

  // Extract HIDDEN_SUBCOMMANDS set
  const hiddenMatch = content.match(
    /export const HIDDEN_SUBCOMMANDS[^=]*=\s*new Set\(\[([\s\S]*?)\]\)/
  );
  const hidden = new Set<string>();
  if (hiddenMatch?.[1]) {
    const matches = hiddenMatch[1].matchAll(/"([^"]+)"/g);
    for (const m of matches) {
      if (m[1]) hidden.add(m[1]);
    }
  }

  // Extract EXPERIMENTAL_SUBCOMMANDS set
  const expMatch = content.match(
    /export const EXPERIMENTAL_SUBCOMMANDS[^=]*=\s*new Set\(\[([\s\S]*?)\]\)/
  );
  const experimental = new Set<string>();
  if (expMatch?.[1]) {
    const matches = expMatch[1].matchAll(/"([^"]+)"/g);
    for (const m of matches) {
      if (m[1]) experimental.add(m[1]);
    }
  }

  // Extract SUBCOMMAND_ALIASES
  // Handles both quoted keys ("cloud-tasks") and unquoted keys (e, a)
  const aliasMatch = content.match(
    /export const SUBCOMMAND_ALIASES[^{]*\{([\s\S]*?)\}/
  );
  const aliases: Record<string, string> = {};
  if (aliasMatch?.[1]) {
    // Match quoted keys: "cloud-tasks": "cloud"
    const quotedMatches = aliasMatch[1].matchAll(/"([^"]+)"\s*:\s*"([^"]+)"/g);
    for (const m of quotedMatches) {
      if (m[1] && m[2]) aliases[m[1]] = m[2];
    }
    // Match unquoted keys: e: "exec"
    const unquotedMatches = aliasMatch[1].matchAll(/\b([a-z])\s*:\s*"([^"]+)"/g);
    for (const m of unquotedMatches) {
      if (m[1] && m[2]) aliases[m[1]] = m[2];
    }
  }

  return { names, hidden, experimental, aliases };
}

function parseHelpFile(content: string): Record<string, string> {
  // Extract SUMMARIES record
  const summariesMatch = content.match(
    /const SUMMARIES[^{]*\{([\s\S]*?)\};/
  );
  const summaries: Record<string, string> = {};
  if (summariesMatch?.[1]) {
    const matches = summariesMatch[1].matchAll(
      /["']?([a-z-]+)["']?\s*:\s*"([^"]+)"/g
    );
    for (const m of matches) {
      if (m[1] && m[2]) summaries[m[1]] = m[2];
    }
  }
  return summaries;
}

function loadRegistry(): CommandRegistry | null {
  // Only skip when the CLI source tree itself is absent (e.g. Vercel builds
  // that don't check out the sibling mogplex-cli repo). If the tree exists
  // but required files are missing, fail loudly — that's a real breakage.
  if (!fs.existsSync(CLI_SRC)) {
    return null;
  }

  const subcommandsPath = path.join(CLI_SRC, "subcommands.ts");
  const helpPath = path.join(CLI_SRC, "help.ts");

  if (!fs.existsSync(subcommandsPath)) {
    throw new Error(`CLI subcommands.ts not found at ${subcommandsPath}`);
  }
  if (!fs.existsSync(helpPath)) {
    throw new Error(`CLI help.ts not found at ${helpPath}`);
  }

  const subcommandsContent = fs.readFileSync(subcommandsPath, "utf-8");
  const helpContent = fs.readFileSync(helpPath, "utf-8");

  const { names, hidden, experimental, aliases } = parseSubcommandsFile(subcommandsContent);
  const summaries = parseHelpFile(helpContent);

  return { names, hidden, experimental, summaries, aliases };
}

// ---------------------------------------------------------------------------
// MDX generation
// ---------------------------------------------------------------------------

interface CommandDoc {
  name: string;
  summary: string;
  isExperimental: boolean;
  aliases: string[];
}

const IMPLEMENTED_SUBCOMMANDS = new Set(["exec", "login", "slash"]);

const EXTRA_SECTIONS: Readonly<Record<string, string[]>> = {
  exec: [
    "## How It Works",
    "",
    "`mogplex exec` runs one non-interactive task and exits with the engine's final exit code.",
    "The prompt is built from the remaining arguments after `exec`.",
    "",
    "If the prompt starts with `/`, the CLI routes it through the slash-command registry instead of the normal engine prompt path.",
    "",
    "## Common Uses",
    "",
    "```bash",
    'mogplex exec "review the staged diff for regressions"',
    'mogplex exec "summarize the repo structure and likely entrypoints"',
    'mogplex exec "/status"',
    "```",
    "",
    "## Related Entry Points",
    "",
    "- `mogplex \"<prompt>\"` is a shortcut for a one-off non-interactive run without spelling `exec`.",
    "- `mogplex` without a prompt launches the interactive terminal UI.",
    "",
    "## Output",
    "",
    "For automation or scripting, combine `exec` with the global output flags such as `--output json`, `--json`, or `--jsonl`.",
  ],
  login: [
    "## Current Behavior",
    "",
    "The current build supports three top-level login paths:",
    "",
    "- `mogplex login` opens the same interactive auth chooser as bare `mogplex`",
    "- `mogplex login mogplex` routes to the same chooser",
    "- `mogplex login status` prints a safe summary of stored credentials without revealing secret material",
    "",
    "## What It Stores",
    "",
    "Browser sign-in stores a Mogplex token in `~/.mogplex/auth.json`.",
    "API-key login stores the selected provider credential there instead.",
    "",
    "## Common Uses",
    "",
    "```bash",
    "mogplex login",
    "mogplex login status",
    "```",
    "",
    "For the full credential precedence rules, use the [Authentication guide](/cli/guides/authentication).",
  ],
  slash: [
    "## Current Behavior",
    "",
    "As a standalone subcommand, `mogplex slash` currently supports listing the slash registry.",
    "If you omit the nested subcommand, it behaves the same as `mogplex slash list`.",
    "",
    "## Common Uses",
    "",
    "```bash",
    "mogplex slash list",
    "mogplex slash list --json",
    'mogplex exec "/status"',
    'mogplex exec "/mcp"',
    "```",
    "",
    "## Important Distinction",
    "",
    "- Use `mogplex slash list` to inspect the registry from the shell.",
    "- Use `mogplex exec \"/...\"` to run a slash command non-interactively.",
    "- Use a live `mogplex` session when you want the normal interactive slash workflow.",
  ],
  review: [
    "## Current Implementation Status",
    "",
    "The command name is present in the CLI help surface, but the standalone `mogplex review` path is not wired yet in the current build.",
    "At the moment, running it can return `Subcommand 'review' is not yet implemented.`",
    "",
    "## Current Alternative",
    "",
    "Use `exec` with an explicit review prompt instead:",
    "",
    "```bash",
    'mogplex exec "review the staged diff for regressions"',
    "```",
  ],
  mcp: [
    "## Current Implementation Status",
    "",
    "The command name is present in the CLI help surface, but the standalone `mogplex mcp` path is not wired yet in the current build.",
    "At the moment, running it can return `Subcommand 'mcp' is not yet implemented.`",
    "",
    "## Current Alternative",
    "",
    "For current MCP visibility, use one of these paths:",
    "",
    "- [Settings](/web/settings) in the web app for shared MCP definitions",
    '- `mogplex exec "/mcp"` for the in-session slash view of configured MCP servers',
  ],
  resume: [
    "## Current Implementation Status",
    "",
    "The command name is present in the CLI help surface, but the standalone `mogplex resume` path is not wired yet in the current build.",
    "At the moment, running it can return `Subcommand 'resume' is not yet implemented.`",
  ],
  fork: [
    "## Current Implementation Status",
    "",
    "The command name is present in the CLI help surface, but the standalone `mogplex fork` path is not wired yet in the current build.",
    "At the moment, running it can return `Subcommand 'fork' is not yet implemented.`",
  ],
};

function generateMdx(cmd: CommandDoc): string {
  const lines: string[] = [];

  // Front matter
  lines.push("---");
  lines.push(`title: ${cmd.name}`);
  lines.push(`description: ${cmd.summary}`);
  lines.push("---");
  lines.push("");
  lines.push("{/* Auto-generated by scripts/gen-cli-reference.ts — do not edit by hand. */}");
  lines.push("");

  // Experimental badge
  if (cmd.isExperimental) {
    lines.push("> **Experimental**: This command is experimental and may change.");
    lines.push("");
  }

  // Synopsis
  lines.push("## Synopsis");
  lines.push("");
  lines.push("```bash");
  lines.push(`mogplex ${cmd.name} [OPTIONS] [ARGS]`);
  lines.push("```");
  lines.push("");

  // Description
  lines.push("## Description");
  lines.push("");
  lines.push(cmd.summary);
  lines.push("");

  if (!IMPLEMENTED_SUBCOMMANDS.has(cmd.name) && !EXTRA_SECTIONS[cmd.name]) {
    lines.push("## Current Implementation Status");
    lines.push("");
    lines.push(
      `The command name is present in the CLI help surface, but the standalone \`mogplex ${cmd.name}\` path is not wired yet in the current build.`,
    );
    lines.push(
      `At the moment, running it can return \`Subcommand '${cmd.name}' is not yet implemented.\``,
    );
    lines.push("");
  }

  // Aliases
  if (cmd.aliases.length > 0) {
    lines.push("## Aliases");
    lines.push("");
    for (const alias of cmd.aliases) {
      lines.push(`- \`${alias}\``);
    }
    lines.push("");
  }

  const extraSections = EXTRA_SECTIONS[cmd.name];
  if (extraSections) {
    lines.push(...extraSections);
    lines.push("");
  }

  // Run `mogplex <cmd> --help` hint — full option lists are owned by the CLI's own help output,
  // not duplicated here, so they never drift.
  lines.push("## Options");
  lines.push("");
  lines.push(`Run \`mogplex ${cmd.name} --help\` to see all supported flags.`);
  lines.push("");

  // See also
  lines.push("## See also");
  lines.push("");
  lines.push("- [All commands](/cli/commands)");
  lines.push("");

  return lines.join("\n");
}

function generateMetaJson(commandNames: string[]): string {
  const pages = ["index", ...commandNames.sort()];
  const meta = {
    title: "Commands",
    defaultOpen: true,
    pages,
  };
  return JSON.stringify(meta, null, 2) + "\n";
}

// ---------------------------------------------------------------------------
// File writing helpers (idempotent - only writes if content changed)
// ---------------------------------------------------------------------------

function writeFileIfChanged(filePath: string, content: string): boolean {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, "utf-8");
    if (existing === content) {
      return false;
    }
  }
  fs.writeFileSync(filePath, content);
  return true;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  console.log("Loading CLI command registry...");
  const registry = loadRegistry();

  if (!registry) {
    console.warn(
      `CLI source tree not found at ${CLI_SRC}. Skipping CLI reference generation; keeping existing generated files.`
    );
    return;
  }

  // Filter to visible commands only
  const visibleCommands = registry.names.filter(
    (name) => !registry.hidden.has(name)
  );

  if (visibleCommands.length === 0) {
    console.error("No discoverable commands found in CLI registry.");
    console.log("Creating placeholder page...");

    const placeholderMdx = `---
title: Commands
description: CLI command reference (placeholder)
---

{/* Auto-generated by scripts/gen-cli-reference.ts — do not edit by hand. */}

No commands were discovered from the CLI registry. This may indicate the registry
structure has changed.
`;
    writeFileIfChanged(path.join(OUTPUT_DIR, "placeholder.mdx"), placeholderMdx);
    writeFileIfChanged(
      path.join(OUTPUT_DIR, "meta.json"),
      JSON.stringify({ title: "Commands", defaultOpen: true, pages: ["index", "placeholder"] }, null, 2) + "\n"
    );
    process.exit(0);
  }

  console.log(`Found ${visibleCommands.length} visible commands.`);

  // Build alias lookup (reverse: command -> aliases)
  const aliasesByCommand: Record<string, string[]> = {};
  for (const [alias, cmd] of Object.entries(registry.aliases)) {
    if (!aliasesByCommand[cmd]) aliasesByCommand[cmd] = [];
    aliasesByCommand[cmd].push(alias);
  }

  // Generate MDX for each command
  const generatedNames: string[] = [];
  let changedCount = 0;
  for (const name of visibleCommands) {
    const cmd: CommandDoc = {
      name,
      summary: registry.summaries[name] ?? "No description available.",
      isExperimental: registry.experimental.has(name),
      aliases: aliasesByCommand[name] ?? [],
    };

    const mdxContent = generateMdx(cmd);
    const outputPath = path.join(OUTPUT_DIR, `${name}.mdx`);
    const changed = writeFileIfChanged(outputPath, mdxContent);
    generatedNames.push(name);
    if (changed) {
      changedCount++;
      console.log(`  Generated: ${name}.mdx`);
    }
  }

  // Generate meta.json
  const metaContent = generateMetaJson(generatedNames);
  const metaChanged = writeFileIfChanged(path.join(OUTPUT_DIR, "meta.json"), metaContent);
  if (metaChanged) {
    changedCount++;
    console.log(`  Generated: meta.json with ${generatedNames.length + 1} pages`);
  }

  if (changedCount === 0) {
    console.log(`Done. All ${generatedNames.length} command pages are up to date.`);
  } else {
    console.log(`Done. Updated ${changedCount} file(s).`);
  }
}

main();
